### ISSUE TITLE
API version mismatch

### ISSUE THREAD

**Issue by andrewdavey** [fdecampredon/jsx-typescript#4]
On loading my typescript project in Visual Studio 2013, I'm getting an Assertion Failed dialog box. I can click Ignore and continue to load the project. Is there something configured incorrectly on my system?

```
API version mismatch: managed version '0.4', script version '0.5'

   at TypeScriptLanguageService.CompilerServices.TypeScriptServicesFactoryProxy.ReportError(String message)
   at TypeScriptLanguageService.CompilerServices.TypeScriptServicesFactoryProxy.InitializeEngine()
   at TypeScriptLanguageService.CompilerServices.TypeScriptServicesFactoryProxy.InitializeJavaScriptEngineIfNecessary()
   at TypeScriptLanguageService.CompilerServices.TypeScriptServicesFactoryProxy.GetFactoryObject(Int32& fileVersion)
   at TypeScriptLanguageService.CompilerServices.TypeScriptGlobalServicesAccessor.CreateProxy(Int32& servicesFileVersion)
   at TypeScriptLanguageService.CompilerServices.TypeScriptServicesAccessorBase.get_Proxy()
   at TypeScriptLanguageService.CompilerServices.TypeScriptGlobalServicesProxy.GetDefaultCompilationSettings()
   at TypeScriptLanguageService.ScriptContext.DefaultCompilationSettingsProvider.GetDefaultCompilationSettings(ITypeScriptGlobalServicesProxy typescriptGlobalServicesProxy)
   at TypeScriptLanguageService.ScriptContext.ScriptContextComputeTask.Run(ITypeScriptGlobalServicesProxy services)
   at TypeScriptLanguageService.CompilerServices.TypeScriptGlobalServicesTask.Run()
   at TypeScriptLanguageService.Threading.BackgroundThreadQueue.<>c__DisplayClass8.<ExecuteOneTask>b__4()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   at TypeScriptLanguageService.VsErrorReport.ExceptionFilter.Guard(Func`1 target, Func`2 filter, Func`2 handler)
   at TypeScriptLanguageService.Threading.BackgroundThreadQueue.ExecuteOneTask(BackgroundTask task)
   at TypeScriptLanguageService.Threading.BackgroundThreadQueue.ExecuteTasks()
   at TypeScriptLanguageService.Threading.BackgroundThreadQueue.Loop()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by fdecampredon** [comment]
:/ the problem is that I started to work on that from master typescript and that there is no visual studio version that manage it, I would prefer to avoid a commit that will make me diverge from typescript in other area than jsx support.

You have 2 solutions there: 
- wait for ts 1.5 release and the vs update that comes with it
- a _hackicsh_ solution would be to update `typescriptServices.js` manually and to search for the line : 

```
ts.servicesVersion = "0.5";
```

And replace the 0.5 with 0.4, I'm pretty sure that the current version of jsx-typescript services does not differ from the 0.4 service api since I'm able to use it in my editor and that it's based on 0.4 api

**Comment by nathggns** [comment]
You could have a branch that has visual studio compatibility? Then update it to be the same as master when typescript 1.5 comes out?

**Comment by fdecampredon** [comment]
@nathggns yeah that's a possibility a dummy branch just for vs support, but could you or @andrewdavey confirm changing the line I specified that everything works fine by just downgrading the string ?

**Comment by andrewdavey** [comment]
Yes, changing the version number to 0.4 works. Thanks.

**Comment by nathggns** [comment]
I don't use visual studio or this project currently. Im just interested in it so I watch it. Sorry I can't help more.

**Comment by fdecampredon** [comment]
no problem @nathggns , thanks @andrewdavey, I'll branch and release a new beta version that just downgrade this string

**Comment by fdecampredon** [comment]
Fixed
